nnpnnn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPNNN -DDELAY=${DELAY} -O3

nnpnn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPNN -DDELAY=${DELAY}

nnpn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPN -DDELAY=${DELAY}

nn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNN  -DDELAY=${DELAY}

nf:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNF  -DDELAY=${DELAY}

n:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DN -DDELAY=${DELAY}

ef:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DEF -DDELAY=${DELAY}

e:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DE -DDELAY=${DELAY}

sf:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DSF -DDELAY=${DELAY}

s:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DS -DDELAY=${DELAY}

si:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DSI -DDELAY=${DELAY}

f:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DF -DDELAY=${DELAY}

debug:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DDEBUG -DNNPNNN
	
