nnpnnn:
	g++ -o asymmetricnnpnnn control.cpp -lpthread -Wall -Wextra -DNNPNNN -DDELAY=${DELAY}  

nnpnn:
	g++ -o asymmetricnnpnn control.cpp -lpthread -Wall -Wextra -DNNPNN -DDELAY=${DELAY}  

nnpn:
	g++ -o asymmetricnnpn control.cpp -lpthread -Wall -Wextra -DNNPN -DDELAY=${DELAY}  

nn:
	g++ -o asymmetricnn control.cpp -lpthread -Wall -Wextra -DNN  -DDELAY=${DELAY}  

nf:
	g++ -o asymmetricnf control.cpp -lpthread -Wall -Wextra -DNF  -DDELAY=${DELAY} 

n:
	g++ -o asymmetricn control.cpp -lpthread -Wall -Wextra -DN -DDELAY=${DELAY} 

ef:
	g++ -o asymmetricef control.cpp -lpthread -Wall -Wextra -DEF -DDELAY=${DELAY}

e:
	g++ -o asymmetrice control.cpp -lpthread -Wall -Wextra -DE -DDELAY=${DELAY}

sf:
	g++ -o asymmetricsf control.cpp -lpthread -Wall -Wextra -DSF -DDELAY=${DELAY}

s:
	g++ -o asymmetrics control.cpp -lpthread -Wall -Wextra -DS -DDELAY=${DELAY}

si:
	g++ -o asymmetricsi control.cpp -lpthread -Wall -Wextra -DSI -DDELAY=${DELAY}

f:
	g++ -o asymmetricf control.cpp -lpthread -Wall -Wextra -DF -DDELAY=${DELAY} 

debug:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DDEBUG -DNNPNNN
	
