nnpnnn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPNNN -DDELAY=${DELAY}


nnpnn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPNN -DDELAY=${DELAY}

nnpn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPN -DDELAY=${DELAY}

nn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNN  -DDELAY=${DELAY}

n:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DN -DDELAY=${DELAY}

e:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DE -DDELAY=${DELAY}

s:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DS -DDELAY=${DELAY}

debug:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DDEBUG -DNNPNNN
	
