nnpnnn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPNNN

nnpnn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPNN
nnpn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPN
nn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNN
n:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DN

debug:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DDEBUG
	
