nnpnnn:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNNPNNN

nnpnn:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNNPNN
nnpn:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNNPN
nn:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNN
n:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DN

nnpnnnc:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNNPNNN -DCACHE_MISSES -L/usr/local/papi/lib -lpapi

nnpnnc:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNNPNN -DCACHE_MISSES  -L/usr/local/papi/lib -lpapi


nnpnc:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNNPN -DCACHE_MISSES -L/usr/local/papi/lib -lpapi


nnc:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNN -DCACHE_MISSES -L/usr/local/papi/lib -lpapi


nc:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DN -DCACHE_MISSES -L/usr/local/papi/lib -lpapi



debug:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DDEBUG
	
