nnpnnn:
	g++ -o asymmetricnnpnnn biasedlock.cpp -lpthread -Wall -Wextra -DNNPNNN -DDELAY=${DELAY}  

nnpnn:
	g++ -o asymmetricnnpnn biasedlock.cpp -lpthread -Wall -Wextra -DNNPNN -DDELAY=${DELAY}  

nnpn:
	g++ -o asymmetricnnpn biasedlock.cpp -lpthread -Wall -Wextra -DNNPN -DDELAY=${DELAY}  

nn:
	g++ -o asymmetricnn biasedlock.cpp -lpthread -Wall -Wextra -DNN  -DDELAY=${DELAY}  

nf:
	g++ -o asymmetricnf biasedlock.cpp -lpthread -Wall -Wextra -DNF  -DDELAY=${DELAY} 

n:
	g++ -o asymmetricn biasedlock.cpp -lpthread -Wall -Wextra -DN -DDELAY=${DELAY} 

ef:
	g++ -o asymmetricef biasedlock.cpp -lpthread -Wall -Wextra -DEF -DDELAY=${DELAY}

e:
	g++ -o asymmetrice biasedlock.cpp -lpthread -Wall -Wextra -DE -DDELAY=${DELAY}

sf:
	g++ -o asymmetricsf biasedlock.cpp -lpthread -Wall -Wextra -DSF -DDELAY=${DELAY}

s:
	g++ -o asymmetrics biasedlock.cpp -lpthread -Wall -Wextra -DS -DDELAY=${DELAY}

si:
	g++ -o asymmetricsi biasedlock.cpp -lpthread -Wall -Wextra -DSI -DDELAY=${DELAY}

f:
	g++ -o asymmetricf biasedlock.cpp -lpthread -Wall -Wextra -DF -DDELAY=${DELAY} 

debug:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DDEBUG -DNNPNNN
	
