nnpnnn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPNNN -DDELAY=${DELAY}  "../../cpucycles-20060326/cpucycles.o"


nnpnn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPNN -DDELAY=${DELAY}  "../../cpucycles-20060326/cpucycles.o"

nnpn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNNPN -DDELAY=${DELAY}  "../../cpucycles-20060326/cpucycles.o"

nn:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DNN  -DDELAY=${DELAY}  "../../cpucycles-20060326/cpucycles.o"

n:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DN -DDELAY=${DELAY}  "../../cpucycles-20060326/cpucycles.o"

e:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DE -DDELAY=${DELAY}  "../../cpucycles-20060326/cpucycles.o"

s:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DS -DDELAY=${DELAY}  "../../cpucycles-20060326/cpucycles.o"

debug:
	g++ -o asymmetric control.cpp -lpthread -Wall -Wextra -DDEBUG -DNNPNNN
	
