nnpnnn:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNNPNNN -L/usr/local/papi/lib -lpapi

nnpnn:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNNPNN -L/usr/local/papi/lib -lpapi
nnpn:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNNPN -L/usr/local/papi/lib -lpapi
nn:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DNN -L/usr/local/papi/lib -lpapi
n:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DN -L/usr/local/papi/lib -lpapi

debug:
	g++ -o asymmetric biasedlock.cpp -lpthread -Wall -Wextra -DDEBUG
	
